#!/bin/bash
git add . && git commit -m "my git shortcut" && git push#!/bin/bash
git add . && git commit -m "my git shortcut" && git push#!/bin/bash
git add . && git commit -m "my git shortcut" && git push
